(function (global) {
  "use strict";

  global.SEASON1_CONFIG = {
    saveKey: "inazumaRoguelikeSeason1Run_v1",
    saveVersion: 1,
    startingLives: 3,
    maxRoster: 15,
    maxInventory: 20,
    startingRoster: 11,
    mapsPerBoss: 1,
    zoneLayers: 6,
    nodeCounts: [2, 3, 3, 2, 3, 2],
    legendaryUnlockBossIndex: 4,
    disabledNodeTypes: ["secondary_match", "coach"],
    lossPolicy: "return_to_previous_match_node",
    nodeWeights: {
      five_v_five: 32,
      item: 15,
      pull_free_agents: 17,
      pull_unlocked_teams: 8,
      pull_legendary: 3,
      trade: 10,
      random: 15,
    },
    stageNodeWeightTiers: [
      { minStage: 1, maxStage: 3, pull_free_agents: 17, pull_unlocked_teams: 8 },
      { minStage: 4, maxStage: 5, pull_free_agents: 8, pull_unlocked_teams: 17 },
      { minStage: 6, maxStage: 7, pull_free_agents: 5, pull_unlocked_teams: 20 },
      { minStage: 8, maxStage: 10, pull_free_agents: 3, pull_unlocked_teams: 22 },
    ],
    hiddenNodeWeights: {
      five_v_five: 20,
      item: 20,
      pull_free_agents: 20,
      pull_unlocked_teams: 15,
      trade: 15,
      pull_legendary: 10,
    },
    nodeLabels: {
      start: { label: "Partenza", icon: "◆", color: "#f6c85f" },
      five_v_five: { label: "Partita 5v5", icon: "5", color: "#e74c3c" },
      item: { label: "Oggetto", icon: "▣", color: "#f1c40f" },
      pull_free_agents: { label: "Pull svincolati", icon: "?", color: "#4aa3df" },
      pull_unlocked_teams: { label: "Pull squadre", icon: "★", color: "#8e67d4" },
      pull_legendary: { label: "Pull leggendario", icon: "✦", color: "#ff9f43" },
      trade: { label: "Scambio", icon: "⇄", color: "#31c48d" },
      random: { label: "Evento casuale", icon: "?", color: "#95a5a6" },
      boss: { label: "Boss", icon: "⚽", color: "#d63031" },
    },
    legendaryCategories: ["Forte", "Elite", "Mondiale", "Leggenda"],
    categoryRanks: {
      Scarso: -1,
      Debole: 0,
      Normale: 2,
      Buono: 3,
      Forte: 4,
      Elite: 5,
      Mondiale: 6,
      Leggenda: 7,
    },
    luckyCharmWeightPerRank: 1.5,
    itemPool: [
      { id: "energy_drink", weight: 10, kind: "consumable", name: "Bevanda energetica", description: "Assegna +2 livelli a un giocatore.", effect: "player_level", amount: 2 },
      { id: "training_manual", weight: 12, kind: "consumable", name: "Manuale di allenamento", description: "Tutta la rosa guadagna +0,5 livello.", effect: "team_level", amount: 0.5 },
      { id: "scout_token", weight: 9, kind: "consumable", name: "Gettone scout", description: "Rigenera i tre giocatori di una pull.", effect: "pull_reroll", amount: 1 },
      { id: "medical_kit", weight: 11, kind: "consumable", name: "Kit medico", description: "Recupera una vita, fino a un massimo di 3.", effect: "restore_life", amount: 1 },
      { id: "intensive_training", weight: 7, kind: "consumable", name: "Allenamento intensivo", description: "Aumenta permanentemente di +3 l’overall attuale e il potenziale massimo di un giocatore, fino a 99.", effect: "potential_boost", amount: 3 },
      { id: "lucky_charm", weight: 3, kind: "consumable", name: "Portafortuna", description: "Rigenera i tre candidati di una Pull svincolati o Pull squadre aumentandone la categoria di un grado. Utilizzabile una sola volta per pull. Non funziona nelle Pull leggendarie o nelle ricompense boss.", effect: "lucky_pull", amount: 1 },
      { id: "boots_attack", weight: 8, kind: "equipment", name: "Scarpini offensivi", description: "Attacco +5.", stat: "attack", bonus: 5 },
      { id: "boots_control", weight: 8, kind: "equipment", name: "Scarpini tecnici", description: "Controllo +5.", stat: "control", bonus: 5 },
      { id: "boots_defense", weight: 8, kind: "equipment", name: "Scarpini difensivi", description: "Difesa +5.", stat: "defense", bonus: 5 },
      { id: "keeper_gloves", weight: 8, kind: "equipment", name: "Guanti da portiere", description: "Parata +5.", stat: "save", bonus: 5 },
      { id: "grit_band", weight: 8, kind: "equipment", name: "Fascia della grinta", description: "Grinta +5.", stat: "grit", bonus: 5 },
      { id: "physical_band", weight: 8, kind: "equipment", name: "Fascia della potenza", description: "Fisico +5.", stat: "physical", bonus: 5 },
      { id: "speed_necklace", weight: 8, kind: "equipment", name: "Collana della velocità", description: "Velocità +5.", stat: "speed", bonus: 5 },
      { id: "stamina_necklace", weight: 8, kind: "equipment", name: "Collana della resistenza", description: "Resistenza +5.", stat: "stamina", bonus: 5 },
    ],
  };
})(globalThis);
