(function (global) {
  "use strict";

  global.SEASON1_CONFIG = {
    saveKey: "inazumaRoguelikeSeason1Run_v2",
    legacySaveKeys: ["inazumaRoguelikeSeason1Run_v1"],
    saveVersion: 2,
    startingLives: 3,
    maxRoster: 15,
    maxInventory: 20,
    startingRoster: 11,
    mapsPerBoss: 1,
    zoneLayers: 6,
    nodeCounts: [2, 3, 3, 2, 3, 2],
    legendaryUnlockBossIndex: 4,
    disabledNodeTypes: ["secondary_match", "coach"],
    lossPolicy: "return_to_previous_match_node",
    nodeWeights: {
      five_v_five: 32,
      item: 15,
      pull_free_agents: 17,
      pull_unlocked_teams: 8,
      pull_legendary: 3,
      trade: 10,
      random: 15,
    },
    stageNodeWeightTiers: [
      { minStage: 1, maxStage: 3, pull_free_agents: 17, pull_unlocked_teams: 8 },
      { minStage: 4, maxStage: 4, pull_free_agents: 8, pull_unlocked_teams: 17 },
      { minStage: 5, maxStage: 5, pull_free_agents: 7, pull_unlocked_teams: 16, pull_legendary: 5 },
      { minStage: 6, maxStage: 7, pull_free_agents: 4, pull_unlocked_teams: 19, pull_legendary: 5 },
      { minStage: 8, maxStage: 10, pull_free_agents: 2, pull_unlocked_teams: 20, pull_legendary: 6 },
    ],
    hiddenNodeWeights: {
      five_v_five: 20,
      item: 20,
      pull_free_agents: 20,
      pull_unlocked_teams: 15,
      trade: 15,
      pull_legendary: 10,
    },
    nodeLabels: {
      start: { label: "Partenza", icon: "◆", color: "#f6c85f" },
      five_v_five: { label: "Partita 5v5", icon: "5", color: "#e74c3c" },
      item: { label: "Oggetto", icon: "▣", color: "#f1c40f" },
      pull_free_agents: { label: "Pull svincolati", icon: "?", color: "#4aa3df" },
      pull_unlocked_teams: { label: "Pull squadre", icon: "★", color: "#8e67d4" },
      pull_legendary: { label: "Pull leggendario", icon: "✦", color: "#ff9f43" },
      trade: { label: "Scambio", icon: "⇄", color: "#31c48d" },
      random: { label: "Evento casuale", icon: "?", color: "#95a5a6" },
      boss: { label: "Boss", icon: "⚽", color: "#d63031" },
    },
    legendaryCategories: ["Forte", "Elite", "Mondiale", "Leggenda"],
    categoryRanks: {
      Scarso: -1,
      Debole: 0,
      Normale: 2,
      Buono: 3,
      Forte: 4,
      Elite: 5,
      Mondiale: 6,
      Leggenda: 7,
    },
    luckyCharmWeightPerRank: 1.5,
    itemPool: [
      { id: "energy_drink", weight: 10, kind: "consumable", name: "Onigiri energetico", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/j/9/j9lr9v-ph1c.png", description: "Aumenta di 2 livelli un giocatore, fino al livello 20.", effect: "player_level", amount: 2 },
      { id: "training_manual", weight: 12, kind: "consumable", name: "Fascia della motivazione", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/d/s/ds-gbxtmuws.png", description: "Aumenta di 0,5 livello tutta la rosa, fino al livello 20.", effect: "team_level", amount: 0.5 },
      { id: "scout_token", weight: 9, kind: "consumable", name: "Visore scout", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/4/g/4guzyjzrxvk.png", description: "Rigenera i tre candidati di un pull normale.", effect: "pull_reroll", amount: 1 },
      { id: "medical_kit", weight: 11, kind: "consumable", name: "Bendaggio sportivo", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/i/j/ij7xzdibdas.png", description: "Recupera una vita, fino a un massimo di 3.", effect: "restore_life", amount: 1 },
      { id: "intensive_training", weight: 7, kind: "consumable", name: "Pesi da allenamento", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/i/y/iyy3nyi8ths.png", description: "Aumenta di 3 l’overall attuale e il potenziale massimo di un giocatore, fino a 99.", effect: "potential_boost", amount: 3 },
      { id: "lucky_charm", weight: 3, kind: "consumable", name: "Talismano portafortuna", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/j/s/jsqmv5wwkvk.png", description: "Migliora di una categoria i tre candidati di una Pull svincolati o Pull squadre. Utilizzabile una sola volta per pull.", effect: "lucky_pull", amount: 1 },
      { id: "boots_attack", weight: 8, kind: "equipment", name: "Scarpini della Fiamma", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/j/o/jomvfg5z3p8.png", description: "Aumenta di 5 la statistica Attacco del giocatore equipaggiato.", stat: "attack", bonus: 5 },
      { id: "boots_control", weight: 8, kind: "equipment", name: "Scarpini del Ghiaccio", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/k/f/kfe9tshkzpc.png", description: "Aumenta di 5 la statistica Controllo del giocatore equipaggiato.", stat: "control", bonus: 5 },
      { id: "boots_defense", weight: 8, kind: "equipment", name: "Scarpini Imperiali", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/x/4/x4xakdeedrm.png", description: "Aumenta di 5 la statistica Difesa del giocatore equipaggiato.", stat: "defense", bonus: 5 },
      { id: "keeper_gloves", weight: 8, kind: "equipment", name: "Guanti Salva-Porta", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/t/q/tq_np8t-bhu.png", description: "Aumenta di 5 la statistica Parata del giocatore equipaggiato.", stat: "save", bonus: 5 },
      { id: "grit_band", weight: 8, kind: "equipment", name: "Bracciale della Grinta", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/g/y/gy4nmcoz_s8.png", description: "Aumenta di 5 la statistica Grinta del giocatore equipaggiato.", stat: "grit", bonus: 5 },
      { id: "physical_band", weight: 8, kind: "equipment", name: "Bracciale della Potenza", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/e/b/ebttgdstz2k.png", description: "Aumenta di 5 la statistica Fisico del giocatore equipaggiato.", stat: "physical", bonus: 5 },
      { id: "speed_necklace", weight: 8, kind: "equipment", name: "Collana dell’Uragano", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/a/l/algd4dnn3lk.png", description: "Aumenta di 5 la statistica Velocità del giocatore equipaggiato.", stat: "speed", bonus: 5 },
      { id: "stamina_necklace", weight: 8, kind: "equipment", name: "Collana dell’Atleta", imageUrl: "https://dxi4wb638ujep.cloudfront.net/1/k/s/z/sztfbzdox00.png", description: "Aumenta di 5 la statistica Resistenza del giocatore equipaggiato.", stat: "stamina", bonus: 5 },
    ],
  };
})(globalThis);
