(function (global) {
  "use strict";

  global.SEASON1_CONFIG = {
    saveKey: "inazumaRoguelikeSeason1Run_v1",
    saveVersion: 1,
    startingLives: 3,
    maxRoster: 15,
    maxInventory: 20,
    startingRoster: 11,
    mapsPerBoss: 1,
    zoneLayers: 6,
    nodeCounts: [2, 3, 3, 2, 3, 2],
    legendaryUnlockBossIndex: 4,
    disabledNodeTypes: ["secondary_match", "coach"],
    lossPolicy: "restore_last_boss_checkpoint",
    nodeWeights: {
      five_v_five: 32,
      item: 15,
      pull_free_agents: 15,
      pull_unlocked_teams: 10,
      pull_legendary: 3,
      trade: 10,
      random: 15,
    },
    nodeLabels: {
      start: { label: "Partenza", icon: "◆", color: "#f6c85f" },
      five_v_five: { label: "Partita 5v5", icon: "5", color: "#e74c3c" },
      item: { label: "Oggetto", icon: "▣", color: "#f1c40f" },
      pull_free_agents: { label: "Pull svincolati", icon: "?", color: "#4aa3df" },
      pull_unlocked_teams: { label: "Pull squadre", icon: "★", color: "#8e67d4" },
      pull_legendary: { label: "Pull leggendario", icon: "✦", color: "#ff9f43" },
      trade: { label: "Scambio", icon: "⇄", color: "#31c48d" },
      random: { label: "Evento casuale", icon: "?", color: "#95a5a6" },
      boss: { label: "Boss", icon: "⚽", color: "#d63031" },
    },
    legendaryCategories: ["Forte", "Elite", "Mondiale", "Leggenda"],
    categoryRanks: {
      Debole: 0,
      Normale: 1,
      Buono: 2,
      Forte: 3,
      Elite: 4,
      Mondiale: 5,
      Leggenda: 6,
    },
    luckyCharmWeightPerRank: 1.5,
    itemPool: [
      { id: "energy_drink", kind: "consumable", name: "Bevanda energetica", description: "Assegna +1 livello a un giocatore.", effect: "player_level", amount: 1 },
      { id: "training_manual", kind: "consumable", name: "Manuale di allenamento", description: "Tutta la rosa guadagna +0,5 livello.", effect: "team_level", amount: 0.5 },
      { id: "scout_token", kind: "consumable", name: "Gettone scout", description: "Rigenera i tre giocatori di una pull.", effect: "pull_reroll", amount: 1 },
      { id: "medical_kit", kind: "consumable", name: "Kit medico", description: "Recupera una vita, fino a un massimo di 3.", effect: "restore_life", amount: 1 },
      { id: "lucky_charm", kind: "consumable", name: "Portafortuna", description: "Migliora le categorie della prossima pull.", effect: "lucky_pull", amount: 1 },
      { id: "boots_attack", kind: "equipment", name: "Scarpini offensivi", description: "Attacco +5.", stat: "attack", bonus: 5 },
      { id: "boots_control", kind: "equipment", name: "Scarpini tecnici", description: "Controllo +5.", stat: "control", bonus: 5 },
      { id: "boots_defense", kind: "equipment", name: "Scarpini difensivi", description: "Difesa +5.", stat: "defense", bonus: 5 },
      { id: "keeper_gloves", kind: "equipment", name: "Guanti da portiere", description: "Parata +5.", stat: "save", bonus: 5 },
      { id: "grit_band", kind: "equipment", name: "Fascia della grinta", description: "Grinta +5.", stat: "grit", bonus: 5 },
      { id: "physical_band", kind: "equipment", name: "Fascia della potenza", description: "Fisico +5.", stat: "physical", bonus: 5 },
      { id: "speed_necklace", kind: "equipment", name: "Collana della velocità", description: "Velocità +5.", stat: "speed", bonus: 5 },
      { id: "stamina_necklace", kind: "equipment", name: "Collana della resistenza", description: "Resistenza +5.", stat: "stamina", bonus: 5 },
    ],
  };
})(globalThis);
