(function (global) {
  "use strict";

  const categories = [
    { id: "training", title: "Allenamento e potenziamenti", icon: "▴", itemIds: ["energy_drink", "training_manual", "intensive_training"] },
    { id: "equipment", title: "Equipaggiamenti", icon: "◆", itemIds: [] },
    { id: "special", title: "Gettoni e oggetti speciali", icon: "✦", itemIds: ["scout_token", "medical_kit", "lucky_charm"] },
  ];

  function create({ getItemPool }) {
    const itemDefinitionById = id => getItemPool().find(candidate => candidate.id === id) || null;
    function resolveItem(itemOrId) { const id = String(typeof itemOrId === "string" ? itemOrId : itemOrId?.itemId || itemOrId?.id || ""); const definition = itemDefinitionById(id); if (definition) return typeof itemOrId === "object" && itemOrId ? { ...itemOrId, ...definition, instanceId: itemOrId.instanceId } : definition; return typeof itemOrId === "object" && itemOrId ? itemOrId : { id, name: "Oggetto", description: "Oggetto non disponibile." }; }
    const inventoryItemIdentity = item => String(item?.itemId || item?.id || item?.effect || item?.name || "unknown_item");
    function inventoryItemCategory(item) { const id = inventoryItemIdentity(item); if (item?.kind === "equipment") return "equipment"; return categories.find(category => category.itemIds.includes(id))?.id || "special"; }
    function groupedInventoryItems(inventory) { const groups = new Map(); (Array.isArray(inventory) ? inventory : []).forEach(item => { const key = inventoryItemIdentity(item); const existing = groups.get(key); if (existing) { existing.quantity += 1; existing.instances.push(item); } else groups.set(key, { key, item, quantity: 1, instances: [item], category: inventoryItemCategory(item) }); }); return [...groups.values()]; }
    function groupedInventoryByCategory(inventory) { const groups = groupedInventoryItems(inventory); return categories.map(category => ({ ...category, items: groups.filter(group => group.category === category.id) })); }
    function groupedOwnedInventoryItems(run) { const backpack = Array.isArray(run?.inventory) ? run.inventory : []; const groups = new Map(groupedInventoryItems(backpack).map(group => [group.key, { ...group, backpackQuantity: group.quantity, equippedCount: 0, equippedEntries: [] }])); const seen = new Set(backpack.map(item => item?.instanceId).filter(Boolean).map(String)); (Array.isArray(run?.roster) ? run.roster : []).forEach(entry => { if (!entry?.equippedItem) return; const item = entry.equippedItem; const key = inventoryItemIdentity(item); const instanceId = item.instanceId ? String(item.instanceId) : ""; const duplicate = instanceId && seen.has(instanceId); const existing = groups.get(key) || { key, item, quantity: 0, backpackQuantity: 0, equippedCount: 0, instances: [], equippedEntries: [], category: inventoryItemCategory(item) }; existing.equippedCount += 1; existing.equippedEntries.push(entry); if (!duplicate) { existing.quantity += 1; if (instanceId) seen.add(instanceId); } groups.set(key, existing); }); return [...groups.values()]; }
    function groupedOwnedInventoryByCategory(run) { const groups = groupedOwnedInventoryItems(run); return categories.map(category => ({ ...category, items: groups.filter(group => group.category === category.id) })); }
    function inventoryOwnershipSummary(run) { const backpack = Array.isArray(run?.inventory) ? run.inventory : []; const equipped = (Array.isArray(run?.roster) ? run.roster : []).filter(entry => entry?.equippedItem); const seen = new Set(); let ownedCount = 0; const count = item => { if (item?.instanceId) { const key = String(item.instanceId); if (seen.has(key)) return; seen.add(key); } ownedCount += 1; }; backpack.forEach(count); equipped.forEach(entry => count(entry.equippedItem)); return { backpackCount: backpack.length, equippedCount: equipped.length, ownedCount, equippedPlayerCount: new Set(equipped.map(entry => String(entry.playerId))).size, consumableCount: backpack.filter(item => resolveItem(item).kind === "consumable").length }; }
    const itemStatLabel = stat => ({ attack: "Attacco", control: "Controllo", defense: "Difesa", save: "Parata", grit: "Grinta", physical: "Fisico", speed: "Velocità", stamina: "Resistenza" })[stat] || stat || "Effetto";
    function inventoryFilterDefinitions(run) { const groups = groupedOwnedInventoryItems(run); const hasKind = kind => groups.some(group => resolveItem(group.item).kind === kind); const hasStat = stat => groups.some(group => resolveItem(group.item).stat === stat); return [{ id: "all", label: "Tutti", count: groups.reduce((sum, group) => sum + group.quantity, 0) }, ...(hasKind("equipment") ? [{ id: "equipment", label: "Equipaggiabili", count: groups.filter(group => resolveItem(group.item).kind === "equipment").reduce((sum, group) => sum + group.quantity, 0) }] : []), ...(hasKind("consumable") ? [{ id: "consumable", label: "Consumabili", count: groups.filter(group => resolveItem(group.item).kind === "consumable").reduce((sum, group) => sum + group.quantity, 0) }] : []), ...["attack", "control", "defense", "save", "grit", "physical", "speed", "stamina"].filter(hasStat).map(stat => ({ id: `stat:${stat}`, label: itemStatLabel(stat), count: groups.filter(group => resolveItem(group.item).stat === stat).reduce((sum, group) => sum + group.quantity, 0) }))]; }
    function inventoryGroupMatchesFilter(group, filterId) { const item = resolveItem(group.item); if (!filterId || filterId === "all") return true; if (filterId === "equipment" || filterId === "consumable") return item.kind === filterId; if (filterId.startsWith("stat:")) return item.stat === filterId.slice(5); return group.category === filterId; }
    return { categories, itemDefinitionById, resolveItem, inventoryItemIdentity, inventoryItemCategory, groupedInventoryItems, groupedInventoryByCategory, groupedOwnedInventoryItems, groupedOwnedInventoryByCategory, inventoryOwnershipSummary, itemStatLabel, inventoryFilterDefinitions, inventoryGroupMatchesFilter };
  }
  global.InventoryModel = { create };
})(globalThis);
