(function (global) {
  "use strict";

  const HOME_SECONDARY_ACTIONS = [
    { id: "open-shop-home", label: "Negozio", description: "Oggetti e potenziamenti", icon: "◆", className: "home-club-action--wide" },
    { id: "open-development-home", label: "Centro di Sviluppo", description: "Potenzia il tuo club", icon: "↗", className: "home-club-action--wide" },
    { id: "open-album-home", label: "Album", description: "Le tue collezioni", icon: "▤", className: "" },
    { id: "open-hall-home", label: "Albo d’Oro", description: "Le squadre campioni", icon: "★", className: "home-club-action--gold" },
    { id: "open-modes-home", label: "Modalità", description: "Altre modalità di gioco", icon: "⚡", className: "home-club-action--wide" },
  ];

  global.HomeView = {
    create({ escapeHtml, normalizeTeamIdentity, savedTeamIdentity, seasonDisplayName, resolvedRosterPlayer, averageOverall, lifeHeartsMarkup, bossTeamLogoUrl, getSeasonDb }) {
      function runFormationLabel(savedRun) { const formation = getSeasonDb()?.formations?.eleven?.find((item) => item.id === savedRun?.formationId); return formation?.formation || formation?.name || savedRun?.formationId || "Da scegliere"; }
      function runHeartsMarkup(savedRun) { return lifeHeartsMarkup(savedRun?.lives); }
      function runAverageOverall(savedRun) { return averageOverall((savedRun?.roster || []).map((entry) => resolvedRosterPlayer(entry.playerId || entry.id)).filter(Boolean)); }
      function homeZoneProgress(savedRun) { const zone = savedRun?.currentZone; if (!zone?.nodes?.length) return 0; const currentNode = zone.nodes.find((node) => node.id === zone.currentNodeId); const finalLayer = Math.max(1, ...zone.nodes.map((node) => Number(node.layer || 0))); return Math.max(0, Math.min(100, Math.round((Number(currentNode?.layer || 0) / finalLayer) * 100))); }
      function homeQuickActionsMarkup() { const actions = HOME_SECONDARY_ACTIONS.map(({ id, label, description, icon, className }) => `
        <button type="button" class="home-club-action ${className}" id="${id}"><span class="home-club-icon" aria-hidden="true">${icon}</span><span class="home-club-copy"><strong>${label}</strong><small>${description}</small></span><span class="home-club-arrow" aria-hidden="true">»</span></button>`).join(""); return `<section class="home-club-section" aria-label="Il tuo club"><div class="home-section-label"><span>⚡</span> Il tuo club</div><nav class="home-club-actions" aria-label="Sezioni principali">${actions}</nav></section>`; }
      function homeTeamCrestMarkup(identity) { const emblem = global.TeamEmblems.resolveTeamEmblem({ teamIdentity: identity, fallbackKind: "user" }); return global.TeamEmblems.teamEmblemMarkup(emblem, { escape: escapeHtml, className: "home-team-emblem" }); }
      function homeIdentityMarkup(savedRun, profileIdentity = savedTeamIdentity()) { const identity = normalizeTeamIdentity(savedRun?.teamIdentity || profileIdentity || {}); const season = savedRun ? global.SeasonRegistry?.get?.(savedRun.seasonId) : null; return `<section class="home-team-banner anime-panel" aria-label="Identità squadra"><div class="home-team-crest">${homeTeamCrestMarkup(identity)}</div><div class="home-team-copy"><h1>${escapeHtml(identity.name)}</h1>${savedRun ? `<p>${escapeHtml(seasonDisplayName(savedRun.seasonId))}</p>${season?.displaySeasonNumber != null ? `<span>Stagione ${escapeHtml(season.displaySeasonNumber)}</span>` : ""}` : ""}</div></section>`; }
      function homeActiveRunMarkup(savedRun) { const seasonDb = getSeasonDb(); const bossIndex = Number(savedRun.bossIndex || 0); const boss = seasonDb?.bossOrder?.[bossIndex]; const bossNumber = bossIndex + 1; const totalBosses = seasonDb?.bossOrder?.length || 10; const zoneProgress = homeZoneProgress(savedRun); const bossLogo = bossTeamLogoUrl(boss); return `<div class="home-content"><section class="home-hero home-active-dashboard" aria-label="Home con run attiva">${homeIdentityMarkup(savedRun)}<article class="home-hub-card home-run-card home-run-panel anime-panel"><div class="home-panel-kicker"><span>⚡</span> Run in corso</div><div class="home-next-boss"><div class="home-boss-identity"><small>Prossimo boss</small><span class="home-boss-logo">${bossLogo ? `<img src="${escapeHtml(bossLogo)}" alt="" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false" /><b hidden aria-hidden="true">B</b>` : "B"}</span><strong>${escapeHtml(boss?.teamName || "Raimon")}</strong></div><div class="home-stage"><small>Stage</small><strong>${escapeHtml(Math.min(bossNumber, totalBosses))}<em>/${escapeHtml(totalBosses)}</em></strong></div></div><div class="home-run-stats"><span><small>Media team</small><strong>${escapeHtml(runAverageOverall(savedRun))}</strong></span><span><small>Formazione</small><strong>${escapeHtml(runFormationLabel(savedRun))}</strong></span><span class="home-zone-stat"><small>Progresso zona</small><strong>${escapeHtml(zoneProgress)}%</strong><i><b style="width:${zoneProgress}%"></b></i></span></div></article><button type="button" class="home-main-cta" id="home-primary-cta"><span aria-hidden="true">⚡</span><strong id="continue-run">Continua la run »</strong></button>${homeQuickActionsMarkup()}</section></div>`; }
      function homeEmptyRunMarkup() { return `<div class="home-content"><section class="home-hero home-empty-dashboard" aria-label="Home senza run attiva">${homeIdentityMarkup(null)}<article class="home-empty-panel anime-panel"><div class="home-panel-kicker"><span>⚡</span> Nessuna run attiva</div><div class="home-empty-copy"><h1>Scrivi la tua leggenda</h1><p>Una nuova avventura ti aspetta.</p></div><button type="button" class="home-main-cta" id="home-primary-cta"><span aria-hidden="true">⚡</span><strong id="choose-run">Entra nel torneo »</strong></button></article>${homeQuickActionsMarkup()}</section></div>`; }
      return { runFormationLabel, runHeartsMarkup, runAverageOverall, homeZoneProgress, homeQuickActionsMarkup, homeTeamCrestMarkup, homeIdentityMarkup, homeActiveRunMarkup, homeEmptyRunMarkup, homeRunCardMarkup: (run) => run ? homeActiveRunMarkup(run) : homeEmptyRunMarkup() };
    },
  };
})(globalThis);
