"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(root, "js/app.js"), "utf8");
const css = fs.readFileSync(path.join(root, "css/game.css"), "utf8");
const indexHtml = fs.readFileSync(path.join(root, "index.html"), "utf8");
assert(indexHtml.includes("js/album-progress.js"), "Album storage module must load before app.js");
assert(appJs.includes("function homeAlbumCardMarkup()") && appJs.includes("Apri Album"), "Home must render a real Album card");
assert(appJs.includes("renderAlbumCollections") && appJs.includes("Inazuma Eleven 1"), "Album collection selection must expose IE1");
assert(appJs.includes("function albumTeamsView()") && appJs.includes("Svincolati"), "Album teams must include free agents");
assert(appJs.includes("data-album-roster") && appJs.includes("data-album-player-entry"), "Album roster must render only the active team grid");
assert(appJs.includes("albumPlayerView") && appJs.includes("player.finalOverall") && appJs.includes("player.finalStats"), "Album cards must use canonical final values");
assert(appJs.includes("playerCard(player") && appJs.includes("album-player-entry"), "Album must wrap the shared playerCard renderer instead of cloning it");
assert(appJs.includes("mode: \"album\", readOnly: true"), "Album card taps must open standard Player Detail in read-only album mode");
assert(appJs.includes("unlockAlbumRecruit(entry.playerId, \"initial_draft\")"), "Initial draft selections and auto-created roster entries must unlock");
assert(appJs.includes("unlockAlbumRecruit(incomingId, \"trade\")"), "Trade incoming player must unlock");
assert((appJs.match(/unlockAlbumRecruit\(player\.playerId, options\.recruitmentSource \|\| source\)/g) || []).length >= 2, "Recruit helper must unlock pull and boss reward additions/replacements");
assert(css.includes(".album-player-entry.is-locked") && css.includes(".album-lock-overlay"), "Locked cards need scoped overlay styles");
assert(css.includes(".album-player-entry.is-unlocked .album-lock-overlay"), "Unlocked cards need distinct scoped state");
assert(css.includes("@media (max-width: 520px)") && css.includes("@media (min-width: 1200px)"), "Album must define mobile and desktop responsive layouts");
const playerCardBody = appJs.slice(appJs.indexOf("function playerCard"), appJs.indexOf("function teamLogoMarkup"));
assert(!playerCardBody.includes("album-lock-overlay") && !playerCardBody.includes("album-player-entry"), "Shared playerCard markup must not contain Album overlay");
console.log("album-ui-test passed");
