"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(root, "js/app.js"), "utf8");
const css = fs.readFileSync(path.join(root, "css/game.css"), "utf8");
const indexHtml = fs.readFileSync(path.join(root, "index.html"), "utf8");
assert(indexHtml.includes("js/album-progress.js"), "Album storage module must load before app.js");
assert(appJs.includes("function homeAlbumCardMarkup()") && appJs.includes("Apri Album"), "Home must render a real Album card");
assert(appJs.includes("renderAlbumCollections") && appJs.includes("Inazuma Eleven 1"), "Album collection selection must expose IE1");
const coverUrl = "https://static.wikia.nocookie.net/inazuma-eleven/images/6/6a/FFI_tournament.png/revision/latest?cb=20141122220203";
assert(appJs.includes(`const ALBUM_COLLECTION_COVER_URL = "${coverUrl}"`), "Album collection card must use the exact remote cover URL");
assert(!appJs.includes("share.google") && !css.includes("share.google"), "Album collection card must not use share.google");
assert(appJs.includes('loading="lazy"') && appJs.includes('decoding="async"'), "Remote collection cover must be lazy-loaded and async-decoded");
assert(appJs.includes("albumProgressPercent(progress)"), "Collection progress percentage must be computed dynamically");
assert(appJs.includes("Math.min(100, Math.max(0"), "Collection progress percentage must be clamped between 0 and 100");
assert(appJs.includes("safeTotal <= 0") && !appJs.includes("NaN%") && !appJs.includes("Infinity%"), "Collection progress percentage must avoid NaN and Infinity");
assert(appJs.includes("album-collection-title") && appJs.includes("album-collection-progress-copy"), "Collection title and progress must be rendered in separate elements");
assert(appJs.includes("album-collection-progress-bar") && appJs.includes("Apri collezione"), "Collection card needs progress bar and clear open affordance");
assert(appJs.includes(`onerror="this.hidden=true; this.parentElement.classList.add('is-fallback');"`), "Collection cover must hide a broken remote image and use fallback styling");
assert(css.includes(".album-collection-cover") && css.includes("aspect-ratio") && css.includes("@media (max-width: 700px)"), "Collection card must have stable responsive cover layout");
assert(appJs.includes('data-album-collection=') && appJs.includes('button.addEventListener("click", () => renderAlbumTeams'), "Entire collection card must remain the clickable navigation surface");

assert(appJs.includes("function albumTeamsView()") && appJs.includes("Svincolati"), "Album teams must include free agents");
assert(appJs.includes("data-album-roster") && appJs.includes("data-album-player-entry"), "Album roster must render only the active team grid");
assert(appJs.includes("albumPlayerView") && appJs.includes("player.finalOverall") && appJs.includes("player.finalStats"), "Album cards must use canonical final values");
assert(appJs.includes("playerCard(player") && appJs.includes("album-player-entry"), "Album must wrap the shared playerCard renderer instead of cloning it");
assert(appJs.includes("mode: \"album\", readOnly: true"), "Album card taps must open standard Player Detail in read-only album mode");
assert(appJs.includes("unlockAlbumRecruit(entry.playerId, \"initial_draft\")"), "Initial draft selections and auto-created roster entries must unlock");
assert(appJs.includes("unlockAlbumRecruit(incomingId, \"trade\")"), "Trade incoming player must unlock");
assert((appJs.match(/unlockAlbumRecruit\(player\.playerId, options\.recruitmentSource \|\| source\)/g) || []).length >= 2, "Recruit helper must unlock pull and boss reward additions/replacements");
assert(css.includes(".album-player-entry.is-locked") && css.includes(".album-lock-overlay"), "Locked cards need scoped overlay styles");
assert(appJs.includes('${isUnlocked ? "" : `<span class="album-lock-overlay album-player-lock">'), "Unlocked Album cards must not render the lock overlay or an unlocked badge");
assert(!css.includes(".album-player-entry.is-unlocked .album-lock-overlay"), "Unlocked Album cards must not style a badge overlay");
assert(css.includes("@media (max-width: 700px)") && css.includes("@media (min-width: 1200px)"), "Album must define mobile and desktop responsive layouts");
const playerCardBody = appJs.slice(appJs.indexOf("function playerCard"), appJs.indexOf("function teamLogoMarkup"));
assert(!playerCardBody.includes("album-lock-overlay") && !playerCardBody.includes("album-player-entry"), "Shared playerCard markup must not contain Album overlay");
console.log("album-ui-test passed");
